version: "3.7"
services:
  smokeping:
    image: magicdude4eva/smokeping
    ports:
      - 8088:80
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      - traefik_public
    deploy:
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public  

        # traefikv2
        - "traefik.http.routers.smokeping.rule=Host(`smokeping.ecom.com.ar`)"
        - "traefik.http.routers.smokeping.entrypoints=http"
        - "traefik.http.services.smokeping.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true